import mongoose from "mongoose";

const qaqcDataSchema = new mongoose.Schema({
  WeightID: String,
  VehicleNo: String,
  PartyName: String,
  ArrivalDate: String,
  VehReportingTime: String,
  FactoryName: String,
  FactoryAddress: String,
  BiltyNo: String,
  TransporterName: String,
  ToLocation: String,
  ArrivalCity: String,

  FirstWeight: Number,
  SecondWeight: Number,
  NetWeight: Number,
  FirstDate: String,
  FirstTime: String,
  SecondDate: String,
  SecondTime: String,

  KgsAlter: String,
  TypeSecond: String,
  TypeFirst: String,

  PONo: String,
  ProductID: Number,
  ProductName: String,
  InspDate: String,
  ProductWeight: Number,
  WtPerBag: Number,
  NoOfBags: Number,

  GreenGrain: Number,
  RedGrain: Number,
  Purity: Number,
  Aflatoxin: Number,
  Broken: Number,
  Moisture: Number,
  Chalky: Number,
  CVOV: Number,
  Choba: Number,
  B1_Percent: Number,
  Damage: Number,
  DDY: Number,
  DB_Percent: Number,
  PassFailDeduction: String,
  DeductionInRs: Number,
  DeductionInKgs: Number,
  DeductionInPercent: Number,
  UnderMilled: Number,
  ForeignM: Number,
  Immature: Number,
  Pecks: Number,
  Paddy: Number,
  Kett: Number,

  Broken1: Number,
  Moisture1: Number,
  Chalky1: Number,
  CVOV1: Number,
  Choba1: Number,
  B1_Percent1: Number,
  Damage1: Number,
  DDY1: Number,
  DB_Percent1: Number,
  PassFailDeduction1: String,
  DeductionInRs1: Number,
  DeductionInKgs1: Number,
  DeductionInPercent1: Number,
  ProductWeight1: Number,
  WtPerBag1: Number,
  NoOfBags1: Number,
  GreenGrain1: Number,
  RedGrain1: Number,
  Purity1: Number,
  Aflatoxin1: Number,
  UnderMilled1: Number,
  ForeignM1: Number,
  Immature1: Number,
  Pecks1: Number,
  Paddy1: Number,
  Kett1: Number,
  PONo1: String,
  ProductID1: Number,
  ProductName1: String,

    // 🔁 Comparison fields
  CmpBroke: Number,
  CmpMoisture: Number,
  CmpChalky: Number,
  CmpCVOV: Number,
  CmpChoba: Number,
  CmpB1Percent: Number,
  CmpDamage: Number,
  CmpDDY: Number,
  CmpDBPercent: Number,
  CmpGreenGrain: Number,
  CmpRedGrain: Number,
  CmpPurity: Number,
  CmpAflatoxin: Number,
  CmpUnderMilled: Number,
  CmpForeignM: Number,
  CmpImmature: Number,
  CmpPecks: Number,
  CmpKett: Number,
  CmpPaddy: Number,
  CmpDedRs: Number,
  CmpDedKgs: Number,
  CmpDedPercent: Number,
  CmpBags: Number,
  CmpWeight: Number,
  // CmpPassFail: Number,

  firstDateTime: { type: Date },
  secondDateTime: { type: Date },

  //missing fields added 24/4/2025
  Location: String,
  Weighbridge: String,
  Type: String,


  UserName: String
}, { timestamps: true }); // Adds createdAt and updatedAt automatically

const qaqcDetails = mongoose.model('qaqcDetails', qaqcDataSchema);

export default qaqcDetails;
