import mongoose from "mongoose";

const qaqcDataSchema = new mongoose.Schema({
  WeightID: String,
  VehicleNo: String,
  PartyName: String,
  ArrivalDate: String,
  VehReportingTime: String,
  FactoryName: String,
  FactoryAddress: String,
  BiltyNo: String,
  TransporterName: String,
  ToLocation: String,
  ArrivalCity: String,

  FirstWeight: Number,
  SecondWeight: Number,
  NetWeight: Number,
  FirstDate: String,
  FirstTime: String,
  SecondDate: String,
  SecondTime: String,

  KgsAlter: String,
  TypeSecond: String,
  TypeFirst: String,

  PONo: String,
  ProductID: Number,
  ProductName: String,
  InspDate: String,
  ProductWeight: String,
  WtPerBag: String,
  NoOfBags: String,

  GreenGrain: String,
  RedGrain: String,
  Purity: String,
  Aflatoxin: String,
  Broken: String,
  Moisture: String,
  Chalky: String,
  CVOV: String,
  Choba: String,
  B1_Percent: String,
  Damage: String,
  DDY: String,
  DB_Percent: String,
  PassFailDeduction: String,
  DeductionInRs: String,
  DeductionInKgs: String,
  DeductionInPercent: String,
  UnderMilled: String,
  ForeignM: String,
  Immature: String,
  Pecks: String,
  Paddy: String,
  Kett: String,

  Broken1: String,
  Moisture1: String,
  Chalky1: String,
  CVOV1: String,
  Choba1: String,
  B1_Percent1: String,
  Damage1: String,
  DDY1: String,
  DB_Percent1: String,
  PassFailDeduction1: String,
  DeductionInRs1: String,
  DeductionInKgs1: String,
  DeductionInPercent1: String,
  ProductWeight1: String,
  WtPerBag1: String,
  NoOfBags1: String,
  GreenGrain1: String,
  RedGrain1: String,
  Purity1: String,
  Aflatoxin1: String,
  UnderMilled1: String,
  ForeignM1: String,
  Immature1: String,
  Pecks1: String,
  Paddy1: String,
  Kett1: String,
  PONo1: String,
  ProductID1: Number,
  ProductName1: String,

  UserName: String
}, { timestamps: true }); // Adds createdAt and updatedAt automatically

const qaqcDetails = mongoose.model('qaqcDetails', qaqcDataSchema);

export default qaqcDetails;
